### ISSUE TITLE
CI/CD do site

### ISSUE THREAD

**Issue by yago-silva** [desenvolve-me/site#5]
Necessário criar os scripts de deploy de CI e CD
- [ ] CI ambiente de QA do site
- [ ] CI ambiente de PRD do site
- [ ] CD ambiente de QA do site
- [ ] CD ambiente de PRD do site

**Comment by yago-silva** [comment]
for deploy in different envs:
https://discuss.circleci.com/t/how-to-deploy-different-environments-with-multiple-contexts/21687/2

```
jobs:
  deploy: &deploy
    ... your deploy setting ...
  deploy-staging:
    <<: *deploy-firebase
  deploy-prod:
    <<: *deploy-firebase
workflows:

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-staging:
          requires:
            - build
            - test
          filters:
            branches:
              only: staging
          context: staging

      - deploy-prod:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
          context: prodution
```
